// LeetCode Problems Data
const problemsData = {
    "Array": [
        { id: 1, name: "Two Sum", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/two-sum/" },
        { id: 2, name: "Best Time to Buy and Sell Stock", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
        { id: 3, name: "Majority Element", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/majority-element/" },
        { id: 4, name: "Contains Duplicate", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/contains-duplicate/" },
        { id: 5, name: "Meeting Rooms", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/meeting-rooms/" },
        { id: 6, name: "Move Zeroes", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/move-zeroes/" },
        { id: 7, name: "Squares of a Sorted Array", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/squares-of-a-sorted-array/" },
        { id: 8, name: "Insert Interval", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/insert-interval/" },
        { id: 9, name: "3Sum", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/3sum/" },
        { id: 10, name: "Product of Array Except Self", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/product-of-array-except-self/" },
        { id: 11, name: "Combination Sum", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/combination-sum/" },
        { id: 12, name: "Merge Intervals", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/merge-intervals/" },
        { id: 13, name: "Sort Colors", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/sort-colors/" },
        { id: 14, name: "Container With Most Water", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/container-with-most-water/" },
        { id: 15, name: "Gas Station", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/gas-station/" },
        { id: 16, name: "Longest Consecutive Sequence", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/longest-consecutive-sequence/" },
        { id: 17, name: "Rotate Array", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/rotate-array/" },
        { id: 18, name: "Contiguous Array", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/contiguous-array/" },
        { id: 19, name: "Subarray Sum Equals K", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/subarray-sum-equals-k/" },
        { id: 20, name: "Meeting Rooms II", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
        { id: 21, name: "3Sum Closest", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/3sum-closest/" },
        { id: 22, name: "Non-overlapping Intervals", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/non-overlapping-intervals/" },
        { id: 23, name: "Employee Free Time", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/employee-free-time/" },
        { id: 24, name: "Sliding Window Maximum", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/sliding-window-maximum/" }
    ],
    "Stack": [
        { id: 1, name: "Valid Parentheses", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/valid-parentheses/" },
        { id: 2, name: "Implement Queue using Stacks", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/implement-queue-using-stacks/" },
        { id: 3, name: "Backspace String Compare", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/backspace-string-compare/" },
        { id: 4, name: "Evaluate Reverse Polish Notation", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
        { id: 5, name: "Min Stack", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/min-stack/" },
        { id: 6, name: "Daily Temperatures", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/daily-temperatures/" },
        { id: 7, name: "Decode String", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/decode-string/" },
        { id: 8, name: "Asteroid Collision", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/asteroid-collision/" },
        { id: 9, name: "Basic Calculator II", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/basic-calculator-ii/" },
        { id: 10, name: "Trapping Rain Water", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/trapping-rain-water/" },
        { id: 11, name: "Basic Calculator", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/basic-calculator/" },
        { id: 12, name: "Largest Rectangle in Histogram", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
        { id: 13, name: "Maximum Frequency Stack", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/maximum-frequency-stack/" },
        { id: 14, name: "Longest Valid Parentheses", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/longest-valid-parentheses/" }
    ],
    "Linked List": [
        { id: 1, name: "Merge Two Sorted Lists", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
        { id: 2, name: "Linked List Cycle", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/linked-list-cycle/" },
        { id: 3, name: "Reverse Linked List", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/reverse-linked-list/" },
        { id: 4, name: "Middle of the Linked List", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/middle-of-the-linked-list/" },
        { id: 5, name: "Palindrome Linked List", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/palindrome-linked-list/" },
        { id: 6, name: "LRU Cache", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/lru-cache/" },
        { id: 7, name: "Remove Nth Node From End of List", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
        { id: 8, name: "Swap Nodes in Pairs", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/swap-nodes-in-pairs/" },
        { id: 9, name: "Odd Even Linked List", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/odd-even-linked-list/" },
        { id: 10, name: "Add Two Numbers", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/add-two-numbers/" },
        { id: 11, name: "Sort List", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/sort-list/" },
        { id: 12, name: "Reorder List", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/reorder-list/" },
        { id: 13, name: "Rotate List", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/rotate-list/" },
        { id: 14, name: "Reverse Nodes in k-Group", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/reverse-nodes-in-k-group/" }
    ],
    "String": [
        { id: 1, name: "Valid Palindrome", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/valid-palindrome/" },
        { id: 2, name: "Valid Anagram", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/valid-anagram/" },
        { id: 3, name: "Longest Palindrome", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/longest-palindrome/" },
        { id: 4, name: "Longest Common Prefix", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/longest-common-prefix/" },
        { id: 5, name: "Longest Substring Without Repeating Characters", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
        { id: 6, name: "String to Integer (atoi)", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/string-to-integer-atoi/" },
        { id: 7, name: "Longest Palindromic Substring", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
        { id: 8, name: "Find All Anagrams in a String", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/find-all-anagrams-in-a-string/" },
        { id: 9, name: "Minimum Window Substring", difficulty: "hard", time: "30 mins", link: "https://leetcode.com/problems/minimum-window-substring/" },
        { id: 10, name: "Group Anagrams", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/group-anagrams/" },
        { id: 11, name: "Longest Repeating Character Replacement", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
        { id: 12, name: "Palindromic Substrings", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/palindromic-substrings/" },
        { id: 13, name: "Encode and Decode Strings", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/encode-and-decode-strings/" },
        { id: 14, name: "Word Break", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/word-break/" }
    ],
    "Binary Tree": [
        { id: 1, name: "Invert Binary Tree", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/invert-binary-tree/" },
        { id: 2, name: "Balanced Binary Tree", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/balanced-binary-tree/" },
        { id: 3, name: "Diameter of Binary Tree", difficulty: "easy", time: "30 mins", link: "https://leetcode.com/problems/diameter-of-binary-tree/" },
        { id: 4, name: "Maximum Depth of Binary Tree", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
        { id: 5, name: "Same Tree", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/same-tree/" },
        { id: 6, name: "Symmetric Tree", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/symmetric-tree/" },
        { id: 7, name: "Subtree of Another Tree", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/subtree-of-another-tree/" },
        { id: 8, name: "Binary Tree Level Order Traversal", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
        { id: 9, name: "Lowest Common Ancestor of a Binary Tree", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
        { id: 10, name: "Binary Tree Right Side View", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/binary-tree-right-side-view/" },
        { id: 11, name: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
        { id: 12, name: "Path Sum II", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/path-sum-ii/" },
        { id: 13, name: "Maximum Width of Binary Tree", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/maximum-width-of-binary-tree/" },
        { id: 14, name: "Binary Tree Zigzag Level Order Traversal", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
        { id: 15, name: "Path Sum III", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/path-sum-iii/" },
        { id: 16, name: "All Nodes Distance K in Binary Tree", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/" },
        { id: 17, name: "Serialize and Deserialize Binary Tree", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
        { id: 18, name: "Binary Tree Maximum Path Sum", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" }
    ],
    "Graph": [
        { id: 1, name: "Flood Fill", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/flood-fill/" },
        { id: 2, name: "01 Matrix", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/01-matrix/" },
        { id: 3, name: "Clone Graph", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/clone-graph/" },
        { id: 4, name: "Course Schedule", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/course-schedule/" },
        { id: 5, name: "Number of Islands", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/number-of-islands/" },
        { id: 6, name: "Rotting Oranges", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/rotting-oranges/" },
        { id: 7, name: "Accounts Merge", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/accounts-merge/" },
        { id: 8, name: "Word Search", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/word-search/" },
        { id: 9, name: "Minimum Height Trees", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/minimum-height-trees/" },
        { id: 10, name: "Pacific Atlantic Water Flow", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/pacific-atlantic-water-flow/" },
        { id: 11, name: "Shortest Path to Get Food", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/shortest-path-to-get-food/" },
        { id: 12, name: "Graph Valid Tree", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/graph-valid-tree/" },
        { id: 13, name: "Course Schedule II", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/course-schedule-ii/" },
        { id: 14, name: "Number of Connected Components in an Undirected Graph", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/" },
        { id: 15, name: "Minimum Knight Moves", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/minimum-knight-moves/" },
        { id: 16, name: "Cheapest Flights Within K Stops", difficulty: "medium", time: "45 mins", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
        { id: 17, name: "Word Ladder", difficulty: "hard", time: "45 mins", link: "https://leetcode.com/problems/word-ladder/" },
        { id: 18, name: "Longest Increasing Path in a Matrix", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/" },
        { id: 19, name: "Word Search II", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/word-search-ii/" },
        { id: 20, name: "Alien Dictionary", difficulty: "hard", time: "45 mins", link: "https://leetcode.com/problems/alien-dictionary/" },
        { id: 21, name: "Bus Routes", difficulty: "hard", time: "45 mins", link: "https://leetcode.com/problems/bus-routes/" }
    ],
    "Binary Search": [
        { id: 1, name: "Binary Search", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/binary-search/" },
        { id: 2, name: "First Bad Version", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/first-bad-version/" },
        { id: 3, name: "Search in Rotated Sorted Array", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
        { id: 4, name: "Time Based Key-Value Store", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/time-based-key-value-store/" },
        { id: 5, name: "Search a 2D Matrix", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/search-a-2d-matrix/" },
        { id: 6, name: "Find Minimum in Rotated Sorted Array", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
        { id: 7, name: "Maximum Profit in Job Scheduling", difficulty: "hard", time: "45 mins", link: "https://leetcode.com/problems/maximum-profit-in-job-scheduling/" },
        { id: 8, name: "Median of Two Sorted Arrays", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" }
    ],
    "Dynamic Programming": [
        { id: 1, name: "Climbing Stairs", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/climbing-stairs/" },
        { id: 2, name: "Maximum Subarray", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/maximum-subarray/" },
        { id: 3, name: "Coin Change", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/coin-change/" },
        { id: 4, name: "Partition Equal Subset Sum", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/partition-equal-subset-sum/" },
        { id: 5, name: "Unique Paths", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/unique-paths/" },
        { id: 6, name: "House Robber", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/house-robber/" },
        { id: 7, name: "Maximum Product Subarray", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/maximum-product-subarray/" },
        { id: 8, name: "Longest Increasing Subsequence", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/longest-increasing-subsequence/" },
        { id: 9, name: "Jump Game", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/jump-game/" },
        { id: 10, name: "Maximal Square", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/maximal-square/" },
        { id: 11, name: "Decode Ways", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/decode-ways/" },
        { id: 12, name: "Combination Sum IV", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/combination-sum-iv/" }
    ],
    "Binary": [
        { id: 1, name: "Add Binary", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/add-binary/" },
        { id: 2, name: "Counting Bits", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/counting-bits/" },
        { id: 3, name: "Number of 1 Bits", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/number-of-1-bits/" },
        { id: 4, name: "Single Number", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/single-number/" },
        { id: 5, name: "Missing Number", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/missing-number/" },
        { id: 6, name: "Reverse Bits", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/reverse-bits/" },
        { id: 7, name: "Find the Duplicate Number", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/find-the-duplicate-number/" }
    ],
    "Math": [
        { id: 1, name: "Roman to Integer", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/roman-to-integer/" },
        { id: 2, name: "Palindrome Number", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/palindrome-number/" },
        { id: 3, name: "Random Pick with Weight", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/random-pick-with-weight/" },
        { id: 4, name: "Pow(x, n)", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/powx-n/" },
        { id: 5, name: "Reverse Integer", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/reverse-integer/" }
    ],
    "Heap": [
        { id: 1, name: "K Closest Points to Origin", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/k-closest-points-to-origin/" },
        { id: 2, name: "Task Scheduler", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/task-scheduler/" },
        { id: 3, name: "Top K Frequent Words", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/top-k-frequent-words/" },
        { id: 4, name: "Find K Closest Elements", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/find-k-closest-elements/" },
        { id: 5, name: "Kth Largest Element in an Array", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
        { id: 6, name: "Find Median from Data Stream", difficulty: "hard", time: "30 mins", link: "https://leetcode.com/problems/find-median-from-data-stream/" },
        { id: 7, name: "Merge k Sorted Lists", difficulty: "hard", time: "30 mins", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
        { id: 8, name: "Smallest Range Covering Elements from K Lists", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/" }
    ],
    "Trie": [
        { id: 1, name: "Implement Trie (Prefix Tree)", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
        { id: 2, name: "Word Break", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/word-break/" },
        { id: 3, name: "Design Add and Search Words Data Structure", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
        { id: 4, name: "Design In-Memory File System", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/design-in-memory-file-system/" }
    ],
    "Recursion": [
        { id: 1, name: "Permutations", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/permutations/" },
        { id: 2, name: "Subsets", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/subsets/" },
        { id: 3, name: "Letter Combinations of a Phone Number", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
        { id: 4, name: "Next Permutation", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/next-permutation/" },
        { id: 5, name: "Generate Parentheses", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/generate-parentheses/" },
        { id: 6, name: "N-Queens", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/n-queens/" }
    ],
    "Matrix": [
        { id: 1, name: "Spiral Matrix", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/spiral-matrix/" },
        { id: 2, name: "Valid Sudoku", difficulty: "medium", time: "35 mins", link: "https://leetcode.com/problems/valid-sudoku/" },
        { id: 3, name: "Rotate Image", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/rotate-image/" },
        { id: 4, name: "Set Matrix Zeroes", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/set-matrix-zeroes/" },
        { id: 5, name: "Sudoku Solver", difficulty: "hard", time: "40 mins", link: "https://leetcode.com/problems/sudoku-solver/" }
    ],
    "Binary Search Tree": [
        { id: 1, name: "Lowest Common Ancestor of a Binary Search Tree", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
        { id: 2, name: "Convert Sorted Array to Binary Search Tree", difficulty: "easy", time: "20 mins", link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/" },
        { id: 3, name: "Validate Binary Search Tree", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/validate-binary-search-tree/" },
        { id: 4, name: "Kth Smallest Element in a BST", difficulty: "medium", time: "25 mins", link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
        { id: 5, name: "Inorder Successor in BST", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/inorder-successor-in-bst/" }
    ],
    "Hash Table": [
        { id: 1, name: "Ransom Note", difficulty: "easy", time: "15 mins", link: "https://leetcode.com/problems/ransom-note/" },
        { id: 2, name: "Insert Delete GetRandom O(1)", difficulty: "medium", time: "20 mins", link: "https://leetcode.com/problems/insert-delete-getrandom-o1/" },
        { id: 3, name: "First Missing Positive", difficulty: "hard", time: "35 mins", link: "https://leetcode.com/problems/first-missing-positive/" }
    ],
    "Queue": [
        { id: 1, name: "Design Hit Counter", difficulty: "medium", time: "30 mins", link: "https://leetcode.com/problems/design-hit-counter/" }
    ]
};

// Topic emojis
const topicEmojis = {
    "Array": "📦",
    "Stack": "🧱",
    "Linked List": "🔗",
    "String": "🔤",
    "Binary Tree": "🌲",
    "Graph": "🌐",
    "Binary Search": "🔍",
    "Dynamic Programming": "🧮",
    "Binary": "🔢",
    "Math": "📐",
    "Heap": "🧺",
    "Trie": "🌲",
    "Recursion": "♻️",
    "Matrix": "🧮",
    "Binary Search Tree": "🌳",
    "Hash Table": "#️⃣",
    "Queue": "🧷"
};
